"""End-to-end test for the `php_current` emitter (T-LAB0.4).

Exercises a `Cell` -> `EmittedFiles` render via real module composition,
asserts byte-determinism (the property `fuzzlab.labgen.gates.regenerate_and_diff`
depends on), and -- when PHP is available on the build host -- syntax-checks
the generated PHP with `php -l` as an extra real-world check (skip-guarded
per PA-0005's pattern, same as the other lanes' integration tests).
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from fuzzlab.labgen.emitters.php_current import PhpCurrentEmitter
from fuzzlab.labgen.schema import Cell, Pipeline, Route, SinkContext

_VULNERABLE_CELL = Cell(
    cell_id="LABGEN-EX-0001",
    vuln_class="sqli",
    stack_profile="php_current",
    route=Route(method="GET", path="/example/product.php"),
    sink_context=SinkContext(family="sql_numeric_literal", required_neutralizations=("sql_syntax_break",)),
    transform=Pipeline.from_list([]),
)

_SECURE_TWIN_CELL = Cell(
    cell_id="LABGEN-EX-0002",
    vuln_class="sqli",
    stack_profile="php_current",
    route=Route(method="GET", path="/example/product.php"),
    sink_context=SinkContext(family="sql_numeric_literal", required_neutralizations=("sql_syntax_break",)),
    transform=Pipeline.from_list(["param_bind"]),
)


def test_supports_the_example_manifest_sqli_cells() -> None:
    emitter = PhpCurrentEmitter()
    assert emitter.supports(_VULNERABLE_CELL.vuln_class, _VULNERABLE_CELL.sink_context) is True
    assert emitter.supports(_SECURE_TWIN_CELL.vuln_class, _SECURE_TWIN_CELL.sink_context) is True


def test_does_not_support_xss_cells_yet_and_a_caller_would_skip() -> None:
    emitter = PhpCurrentEmitter()
    xss_cell = Cell(
        cell_id="LABGEN-EX-0003",
        vuln_class="xss",
        stack_profile="php_current",
        route=Route(method="GET", path="/example/profile.php"),
        sink_context=SinkContext(family="html_attribute_unquoted", required_neutralizations=("html_tag_break",)),
        transform=Pipeline.from_list(["html_entity_escape"]),
    )
    assert emitter.supports(xss_cell.vuln_class, xss_cell.sink_context) is False
    with pytest.raises(ValueError):
        emitter.render(xss_cell)


def test_render_produces_exactly_one_page_file() -> None:
    emitter = PhpCurrentEmitter()
    files = emitter.render(_VULNERABLE_CELL)
    assert len(files) == 1
    assert files[0].path == "generated/labgen-ex-0001.php"
    assert files[0].role == "page"
    assert files[0].content.startswith(b"<?php\n")


def test_render_is_byte_deterministic_across_two_calls() -> None:
    emitter = PhpCurrentEmitter()
    first = emitter.render(_VULNERABLE_CELL)
    second = emitter.render(_VULNERABLE_CELL)
    assert first == second
    assert first[0].content == second[0].content


def test_vulnerable_cell_renders_raw_concatenation_sql() -> None:
    emitter = PhpCurrentEmitter()
    content = emitter.render(_VULNERABLE_CELL)[0].content.decode("utf-8")
    assert '"SELECT * FROM products WHERE id = " . $id' in content
    assert "prepare(" not in content


def test_secure_twin_renders_param_bind_and_the_diff_is_only_the_transform_region() -> None:
    emitter = PhpCurrentEmitter()
    vulnerable = emitter.render(_VULNERABLE_CELL)[0].content.decode("utf-8")
    secure = emitter.render(_SECURE_TWIN_CELL)[0].content.decode("utf-8")

    assert "$stmt = $pdo->prepare(" in secure
    assert "$stmt->execute([$id])" in secure
    assert vulnerable != secure

    # Minimal-pair sanity check: strip each side's own cell_id/module-list
    # comment lines (which necessarily differ -- they name the cell and the
    # composed op list) and confirm the source-extraction and function-wrap
    # lines are otherwise identical between the twins; only the
    # transform/sink body differs.
    def _body_lines(src: str) -> list[str]:
        return [
            line
            for line in src.splitlines()
            if not line.startswith("// Generated by") and not line.startswith("// Module composition:")
        ]

    vuln_lines = _body_lines(vulnerable)
    secure_lines = _body_lines(secure)
    assert vuln_lines[0] == secure_lines[0] == "<?php"
    # Same function signature / same source-extraction line in both twins.
    assert any(line.strip() == "$id = isset($_GET['id']) ? $_GET['id'] : null;" for line in vuln_lines)
    assert any(line.strip() == "$id = isset($_GET['id']) ? $_GET['id'] : null;" for line in secure_lines)


@pytest.mark.skipif(shutil.which("php") is None, reason="php CLI not available on this build host (PA-0005 pattern)")
@pytest.mark.parametrize("cell", [_VULNERABLE_CELL, _SECURE_TWIN_CELL])
def test_generated_php_is_syntactically_valid(cell: Cell) -> None:
    emitter = PhpCurrentEmitter()
    content = emitter.render(cell)[0].content
    with tempfile.TemporaryDirectory() as tmpdir:
        php_path = Path(tmpdir) / "cell.php"
        php_path.write_bytes(content)
        result = subprocess.run(
            ["php", "-l", str(php_path)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0, f"php -l failed:\nstdout={result.stdout}\nstderr={result.stderr}"
