"""Tests for `core.fingerprint.identify_technologies()` — the additive, multi-signal
web application/service fingerprinter. `fingerprint()`/`Fingerprint` (the original
single-value-per-category detector) are covered separately in
`tests/test_fewer_requests.py` and are deliberately untouched by this feature.
"""
from fuzzlab.core.fingerprint import Signal, identify_technologies


def test_server_and_language_from_headers():
    signals = identify_technologies(
        headers={"Server": "nginx/1.25.3", "X-Powered-By": "PHP/8.3"})
    by_name = {s.name: s for s in signals}
    assert by_name["nginx"].category == "server"
    assert by_name["nginx"].version == "1.25.3"
    assert by_name["PHP"].category == "language"
    assert by_name["PHP"].version == "8.3"


def test_wordpress_generator_tag_beats_asset_path_confidence():
    body = ('<meta name="generator" content="WordPress 6.4">'
            '<script src="/wp-content/themes/x/app.js"></script>')
    signals = identify_technologies(headers={}, body=body)
    wp = [s for s in signals if s.name == "WordPress"]
    assert len(wp) == 1                                    # deduped by (category, name)
    assert wp[0].version == "6.4"
    assert wp[0].confidence == 0.95                         # the stronger signature won


def test_jquery_version_extracted_from_script_src():
    signals = identify_technologies(
        headers={}, body='<script src="/static/jquery-3.6.0.min.js"></script>')
    jq = next(s for s in signals if s.name == "jQuery")
    assert jq.category == "js-library"
    assert jq.version == "3.6.0"


def test_cookie_only_signal_is_low_confidence():
    signals = identify_technologies(headers={"Set-Cookie": "connect.sid=abc; Path=/"})
    express = next(s for s in signals if s.name == "Express")
    assert express.confidence < 0.7                         # cookie-name-only is weak


def test_waf_and_dbms_signals():
    signals = identify_technologies(
        headers={"CF-RAY": "abc123"},
        body="You have an error in your SQL syntax near")
    names = {(s.category, s.name) for s in signals}
    assert ("waf-cdn", "Cloudflare") in names
    assert ("dbms", "MySQL") in names


def test_modsecurity_block_page_detected():
    signals = identify_technologies(
        headers={}, body="This error was generated by Mod_Security.")
    assert any(s.name == "ModSecurity" and s.category == "waf-cdn" for s in signals)


def test_no_signals_for_a_blank_response():
    assert identify_technologies(headers={}, body="") == []


def test_source_url_is_attached_to_every_signal():
    signals = identify_technologies(
        headers={"Server": "Apache"}, source_url="http://x/page")
    assert signals and all(s.source_url == "http://x/page" for s in signals)


def test_multiple_independent_technologies_all_reported():
    body = ('<meta name="generator" content="Drupal 10">'
            '<div ng-version="17.0.1"></div>'
            '<link href="bootstrap.min.css">')
    signals = identify_technologies(headers={}, body=body)
    names = {s.name for s in signals}
    assert {"Drupal", "Angular", "Bootstrap"} <= names


def test_signal_is_a_frozen_dataclass_with_expected_fields():
    s = Signal(category="server", name="nginx", version="1.2", confidence=0.9,
              evidence="x", source_url=None)
    assert (s.category, s.name, s.version, s.confidence) == ("server", "nginx", "1.2", 0.9)
