"""The ``route`` accumulator module for ``routes/web.php`` (Addendum D).

Per ``CR-LAB-0001`` Addendum D, an accumulator is a module category VTSG
doesn't have: cardinality ``"accumulator"``, one fragment per cell, merged
into a single stack-level file. The determinism invariant Addendum D adds
for this category is explicit and load-bearing:

    "accumulator fragments must be sorted by cell ID before rendering
    (unsorted, adding one cell reshuffles the routes file and breaks the
    byte-identical-source gate)"

:class:`RouteAccumulator` is intentionally the *only* place that assembles
``routes/web.php``: :meth:`RouteAccumulator.fragment_for_cell` produces one
cell's route-registration line (called from
:meth:`~fuzzlab.labgen.emitters.php_laravel.LaravelEmitter.render`, per
cell) and :meth:`RouteAccumulator.render_file` assembles the whole file from
however many fragments have been collected, **always sorting by cell ID at
call time** -- never trusting the order fragments were collected in. Calling
:meth:`render_file` twice with the same fragment dict (regardless of the
dict's own insertion order -- Python dicts preserve insertion order, which
is exactly the append-order trap Addendum D warns about) must be, and is,
byte-identical.

**Why this lives outside ``Emitter.render()``'s per-cell return value:**
``fuzzlab.labgen.conformance.tier3.render_whole_sample`` -- the shared,
stack-agnostic Tier-3 driver every emitter's conformance suite reuses --
merges every cell's ``EmittedFiles`` into one ``dict[path, bytes]`` and
**raises** if two cells emit the same path (a real, useful invariant for
``php_current``'s one-file-per-cell model, where two different paths
colliding is always a bug). An accumulator is the one legitimate case where
multiple cells *are supposed to* target the same path, so
``render()``-per-cell cannot return the merged ``routes/web.php`` directly
without either breaking that shared invariant for every future accumulator-
using emitter, or requiring an out-of-scope change to
``fuzzlab/labgen/conformance/tier3.py`` (owned by a sibling lane, and a
generic fix belongs with whichever lane needs it for a second accumulator-
bearing stack, not smuggled into this one's foundation work). Per-cell
``render()`` instead returns each cell's own **fragment** at a per-cell path
(see ``LaravelEmitter.render``'s ``"route_fragment"``-role file); assembling
the real ``routes/web.php`` is a whole-manifest step
(:func:`assemble_routes_file`), exercised directly by this lane's own tests
and documented here as the pattern a future multi-cell Tier-3 run should
follow until/unless a sibling lane extends ``tier3.py`` with accumulator-
aware merging.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping

from fuzzlab.labgen.emitter import EmittedFile

_HEADER = (
    "<?php\n"
    "// Generated by fuzzlab.labgen.emitters.php_laravel -- routes/web.php.\n"
    "// One line per cell, sorted by cell_id (CR-LAB-0001 Addendum D's\n"
    "// accumulator-determinism rule) -- never by append/iteration order.\n"
    "\n"
    "use Illuminate\\Support\\Facades\\Route;\n"
    "\n"
)


class RouteAccumulator:
    """The ``route``-category accumulator module for ``routes/web.php``."""

    name = "route"
    category = "route"
    cardinality = "accumulator"

    def fragment_for_cell(self, *, cell_id: str, controller_class: str, url_path: str) -> str:
        """One cell's route-registration line.

        ``url_path`` is derived from the cell ID (see
        ``LaravelEmitter._url_path_for_cell``), not the manifest's
        ``cell.route.path`` verbatim: a vulnerable cell and its secure twin
        share one logical page (``cell.route.path``) but are two distinct
        cells that must coexist as two distinct routes in one generated
        build -- exactly how ``php_current`` already gives twins two
        distinct *files* (``generated/<cell_id>.php`` each) while both
        annotate the same logical ``cell.route.path`` in a comment.
        """
        return (
            f"Route::get('{url_path}', [\\App\\Http\\Controllers\\{controller_class}::class, 'show'])"
            f"; // cell: {cell_id}"
        )

    def render_file(self, fragments: Mapping[str, str]) -> str:
        """Assemble the whole ``routes/web.php`` from ``{cell_id: fragment}``.

        Always sorts by ``cell_id`` (the mapping key) before joining --
        regardless of the mapping's own iteration/insertion order -- so two
        calls with the same fragment set are byte-identical no matter what
        order the fragments were collected in.
        """
        sorted_lines = [fragments[cell_id] for cell_id in sorted(fragments)]
        body = "\n".join(sorted_lines)
        return _HEADER + (body + "\n" if body else "")


def assemble_routes_file(fragments: Mapping[str, str]) -> EmittedFile:
    """Build the final, whole-manifest ``routes/web.php``
    :class:`~fuzzlab.labgen.emitter.EmittedFile` from a cell-id-keyed
    fragment map. A thin wrapper over :meth:`RouteAccumulator.render_file`
    for callers (tests, a future whole-lab build driver) that want the
    ``EmittedFile`` shape directly."""
    accumulator = RouteAccumulator()
    content = accumulator.render_file(fragments)
    return EmittedFile(path="routes/web.php", content=content.encode("utf-8"), role="route")


def collect_fragments(accumulator: RouteAccumulator, cells: Iterable[tuple[str, str, str]]) -> dict[str, str]:
    """Convenience: build the ``{cell_id: fragment}`` map for a batch of
    ``(cell_id, controller_class, url_path)`` triples, in whatever order
    ``cells`` iterates -- :meth:`RouteAccumulator.render_file` sorts
    regardless, so callers never need to pre-sort ``cells`` themselves."""
    return {
        cell_id: accumulator.fragment_for_cell(cell_id=cell_id, controller_class=controller_class, url_path=url_path)
        for cell_id, controller_class, url_path in cells
    }
