<?php
// idiomatic-4-altered.php
// MANUFACTURED per docs/VULN_CORPUS_PAIR_MANUFACTURING_PLAN.md's "Per-pair
// mechanics" -- derived from vulnerable-4-altered.php's own real
// structure. A distinct mitigation technique from idiomatic-1.php's
// extension+finfo-allowlist approach: the uploaded bytes are actually
// decoded and re-encoded as a fresh image via GD before being saved,
// which strips any non-image data (e.g. a PHP payload appended after a
// valid image trailer, or an EXIF-embedded payload) that a pure
// mimetype/extension check would let through untouched.
$tmpPath = $_FILES['avatar']['tmp_name'] ?? '';

$imageInfo = @getimagesize($tmpPath);
if ($imageInfo === false) {
    http_response_code(415);
    echo json_encode(['error' => 'not a valid image']);
    exit;
}

$allowed = [
    IMAGETYPE_JPEG => ['imagecreatefromjpeg', 'imagejpeg', '.jpg'],
    IMAGETYPE_PNG => ['imagecreatefrompng', 'imagepng', '.png'],
];

$type = $imageInfo[2];
if (!isset($allowed[$type])) {
    http_response_code(415);
    echo json_encode(['error' => 'unsupported image type']);
    exit;
}

[$decodeFn, $encodeFn, $ext] = $allowed[$type];
$image = $decodeFn($tmpPath);

// Re-encoding from decoded pixel data discards anything appended to the
// original file outside the actual image structure -- the stored file's
// bytes are entirely regenerated by GD, not a copy of what was uploaded.
$dest = __DIR__ . '/avatars/' . bin2hex(random_bytes(16)) . $ext;
$encodeFn($image, $dest);
imagedestroy($image);

echo json_encode(['status' => 'uploaded', 'path' => $dest]);
