"""The ``route`` accumulator module for ``config/routes.rb`` (mirrors
``php_laravel.route_accumulator``'s ``CR-LAB-0001`` Addendum D pattern,
adapted for Rails' own routing DSL rather than assuming Laravel's
``Route::get(...)`` syntax maps directly).

Rails' DSL differs from Laravel's in the shape that matters here: a
Laravel route names its controller action as a PHP array/class-const pair
(``[Controller::class, 'method']``); Rails names it as a single ``to:``
string, ``"controller#action"`` (snake_case, pluralization-free controller
path -- Rails' router does not require the file to live under
``app/controllers/<name>_controller.rb`` to *route*, but this emitter's own
controller-naming convention, in ``__init__.py``, keeps the two in lockstep
so every registered route resolves to a real, emitted controller file).

Same determinism invariant as the Laravel accumulator: fragments are always
sorted by cell ID before rendering, never by insertion/append order, so
adding one cell cannot reshuffle -- and therefore invalidate the
byte-identical-source gate for -- every other cell's line in the file.
"""

from __future__ import annotations

import re
from collections.abc import Mapping

from fuzzlab.labgen.emitter import EmittedFile


class DuplicateRouteError(ValueError):
    """Raised when two cells' route fragments register the same URL -- see
    :meth:`RouteAccumulator.render_file`."""


#: The URL inside one ``<verb> '<path>', to: ...`` registration line.
#: Anchored on the exact prefix this module itself emits (PA-0022: a
#: mechanical match must not be a loose substring).
_ROUTE_URL_RE = re.compile(r"^\s*[a-z]+\s+'([^']*)'")

_HEADER = (
    "# Generated by fuzzlab.labgen.emitters.ruby_rails -- config/routes.rb.\n"
    "# One line per cell, sorted by cell_id (CR-LAB-0001 Addendum D's\n"
    "# accumulator-determinism rule) -- never by append/iteration order.\n"
    "\n"
    "Rails.application.routes.draw do\n"
    '  get "up" => "rails/health#show", as: :rails_health_check\n'
    "\n"
)

_FOOTER = "end\n"


class RouteAccumulator:
    """The ``route``-category accumulator module for ``config/routes.rb``."""

    name = "route"
    category = "route"
    cardinality = "accumulator"

    #: HTTP methods a route line may be registered with -- Rails' router DSL
    #: exposes one lowercase top-level helper per method, same shape as
    #: Laravel's ``Route`` facade.
    _METHOD_HELPERS: dict[str, str] = {
        "GET": "get",
        "POST": "post",
        "PUT": "put",
        "PATCH": "patch",
        "DELETE": "delete",
    }

    def fragment_for_cell(
        self, *, cell_id: str, controller_name: str, url_path: str, method: str = "GET", action: str = "show"
    ) -> str:
        """One route-registration line.

        ``url_path``/``method`` are decided entirely by the caller -- this
        method never derives a URL or a method itself, so the route that
        gets registered and the route a caller/test probes cannot drift
        apart (PA-0003/PA-0021), mirroring the Laravel accumulator's own
        contract.

        ``controller_name`` is the Rails controller path Rails' router
        expects after ``#`` (e.g. ``"cell_labgen_rr_0001"`` for
        ``app/controllers/cell_labgen_rr_0001_controller.rb``'s
        ``CellLabgenRr0001Controller``) -- never a fully-qualified class
        name, unlike Laravel's ``[Controller::class, 'action']`` array
        form, because Rails' own ``to:`` string routing convention does not
        take one.
        """
        helper = self._METHOD_HELPERS.get(method.upper())
        if helper is None:
            raise ValueError(
                f"{cell_id}: no Rails route helper for HTTP method {method!r} "
                f"-- known methods: {sorted(self._METHOD_HELPERS)}"
            )
        return (
            f"  {helper} '{url_path}', to: '{controller_name}#{action}'"
            f" # cell: {cell_id}"
        )

    def render_file(self, fragments: Mapping[str, str]) -> str:
        """Assemble the whole ``config/routes.rb`` from ``{cell_id:
        fragment}``, always sorting by ``cell_id`` at call time -- never
        trusting the mapping's own insertion order. Byte-identical for two
        calls with the same fragment set, regardless of collection order.

        Raises :class:`DuplicateRouteError` if two cells' fragments register
        the same URL -- Rails would silently dispatch only the first
        matching route, leaving the second cell unreachable, exactly the
        same defense-in-depth check the Laravel accumulator performs.
        """
        by_url: dict[str, list[str]] = {}
        for cell_id in sorted(fragments):
            match = _ROUTE_URL_RE.match(fragments[cell_id])
            if match:
                by_url.setdefault(match.group(1), []).append(cell_id)
        collisions = {url: ids for url, ids in by_url.items() if len(ids) > 1}
        if collisions:
            raise DuplicateRouteError(
                "config/routes.rb would register the same URL for more than one cell, so all "
                "but the first would be unreachable: "
                + "; ".join(f"{url!r} <- {', '.join(ids)}" for url, ids in sorted(collisions.items()))
            )
        sorted_lines = [fragments[cell_id] for cell_id in sorted(fragments)]
        body = "\n".join(sorted_lines)
        return _HEADER + (body + "\n" if body else "") + _FOOTER


def assemble_routes_file(fragments: Mapping[str, str]) -> EmittedFile:
    """Build the final, whole-manifest ``config/routes.rb``
    :class:`~fuzzlab.labgen.emitter.EmittedFile` from a cell-id-keyed
    fragment map -- a thin wrapper over :meth:`RouteAccumulator.render_file`,
    mirroring the Laravel accumulator's own convenience function."""
    accumulator = RouteAccumulator()
    content = accumulator.render_file(fragments)
    return EmittedFile(path="config/routes.rb", content=content.encode("utf-8"), role="route")
