"""The ``route`` accumulator module for ``config/routes.rb`` (mirrors
``php_laravel.route_accumulator``'s ``CR-LAB-0001`` Addendum D pattern,
adapted for Rails' own routing DSL rather than assuming Laravel's
``Route::get(...)`` syntax maps directly).

Rails' DSL differs from Laravel's in the shape that matters here: a
Laravel route names its controller action as a PHP array/class-const pair
(``[Controller::class, 'method']``); Rails names it as a single ``to:``
string, ``"controller#action"`` (snake_case, pluralization-free controller
path -- Rails' router does not require the file to live under
``app/controllers/<name>_controller.rb`` to *route*, but this emitter's own
controller-naming convention, in ``__init__.py``, keeps the two in lockstep
so every registered route resolves to a real, emitted controller file).

Same determinism invariant as the Laravel accumulator: fragments are always
sorted by cell ID before rendering, never by insertion/append order, so
adding one cell cannot reshuffle -- and therefore invalidate the
byte-identical-source gate for -- every other cell's line in the file.
"""

from __future__ import annotations

import re
from collections.abc import Mapping

from fuzzlab.labgen.emitter import EmittedFile


class DuplicateRouteError(ValueError):
    """Raised when two cells' route fragments register the same URL -- see
    :meth:`RouteAccumulator.render_file`."""


#: The URL inside one ``<verb> '<path>', to: ...`` registration line.
#: Anchored on the exact prefix this module itself emits (PA-0022: a
#: mechanical match must not be a loose substring).
_ROUTE_URL_RE = re.compile(r"^\s*[a-z]+\s+'([^']*)'")

#: A ``controller#action`` routing target (lowercase snake_case, PA-0022).
_TO_RE = re.compile(r"[a-z][a-z0-9_]*#[a-z][a-z0-9_]*")

#: One registration line of a rendered ``config/routes.rb`` (this module's
#: own two emitted forms): ``<verb> '<path>', to: '<target>'`` and the
#: health check's ``get "up" => "rails/health#show"``.
_SERVED_ROUTE_RE = re.compile(
    r"""^\s*(get|post|put|patch|delete)\s+(?:'([^']*)',\s*to:\s*'([^']*)'|"([^"]*)"\s*=>\s*"([^"]*)")"""
)

#: Fixed, non-generated routes for "ForgeCart"'s surrounding inert/static
#: pages (Phase C, `docs/LAB_MULTI_CATEGORY_SECOND_TARGETS_PLAN.md` §4/§9.5
#: -- CC-LAB-0077/FR-LAB-81). These exist so the assembled app reads as a
#: real, coherent Shopify-style merchant storefront + admin, not a bag of
#: disconnected illustrative cell endpoints -- but they carry no
#: vulnerability, so they are fixed lines here (mirroring the health-check
#: line above) rather than anything a `Cell`/manifest ever generates. Their
#: controllers (`StorefrontController`/`AdminController`) live in the
#: checked-in skeleton (`stack/skeleton/app/controllers/`), not in any
#: emitted output -- so this constant is the one place their routing is
#: declared, kept in lockstep with those two files by hand (PA-0003/PA-0021
#: applies to this fixed set exactly as it does to per-cell routes: a route
#: named here with no matching controller action would 404 for real).
#
#: CC-LAB-0245 (Browsable Labs Lane 5) adds ``/catalog`` -- the page listing
#: the illustrative ``/cell/*`` routes (design contract point 5), built at
#: request time from Rails' own route table (``StorefrontController#catalog``).
_STATIC_APP_ROUTES = (
    "  get '/', to: 'storefront#home'",
    "  get '/products', to: 'storefront#products'",
    "  get '/cart', to: 'storefront#cart'",
    "  get '/catalog', to: 'storefront#catalog'",
    "  get '/admin', to: 'admin#dashboard'",
    "  get '/admin/orders', to: 'admin#orders'",
)

_HEADER = (
    "# Generated by fuzzlab.labgen.emitters.ruby_rails -- config/routes.rb.\n"
    "# One line per cell, sorted by cell_id (CR-LAB-0001 Addendum D's\n"
    "# accumulator-determinism rule) -- never by append/iteration order.\n"
    "#\n"
    "# The fixed block right below (before the health check) is ForgeCart's\n"
    "# own inert app-identity routes (Phase C) -- not derived from any cell,\n"
    "# see `_STATIC_APP_ROUTES`'s own docstring above.\n"
    "\n"
    "Rails.application.routes.draw do\n"
    + "\n".join(_STATIC_APP_ROUTES) + "\n"
    "\n"
    '  get "up" => "rails/health#show", as: :rails_health_check\n'
    "\n"
)

_FOOTER = "end\n"


class RouteAccumulator:
    """The ``route``-category accumulator module for ``config/routes.rb``."""

    name = "route"
    category = "route"
    cardinality = "accumulator"

    #: HTTP methods a route line may be registered with -- Rails' router DSL
    #: exposes one lowercase top-level helper per method, same shape as
    #: Laravel's ``Route`` facade.
    _METHOD_HELPERS: dict[str, str] = {
        "GET": "get",
        "POST": "post",
        "PUT": "put",
        "PATCH": "patch",
        "DELETE": "delete",
    }

    def fragment_for_cell(
        self,
        *,
        cell_id: str,
        controller_name: str,
        url_path: str,
        method: str = "GET",
        action: str = "show",
        get_page: str | None = None,
    ) -> str:
        """One route-registration line.

        ``url_path``/``method`` are decided entirely by the caller -- this
        method never derives a URL or a method itself, so the route that
        gets registered and the route a caller/test probes cannot drift
        apart (PA-0003/PA-0021), mirroring the Laravel accumulator's own
        contract.

        ``controller_name`` is the Rails controller path Rails' router
        expects after ``#`` (e.g. ``"cell_labgen_rr_0001"`` for
        ``app/controllers/cell_labgen_rr_0001_controller.rb``'s
        ``CellLabgenRr0001Controller``) -- never a fully-qualified class
        name, unlike Laravel's ``[Controller::class, 'action']`` array
        form, because Rails' own ``to:`` string routing convention does not
        take one.

        ``get_page`` (CC-LAB-0245): a checked-in skeleton ``controller#action``
        that answers ``GET`` on the same URL -- a real page's form page or an
        api's ``fetch()`` client page. It is emitted as a separate line
        *before* the cell's own verb line, so the duplicate-URL check (keyed on
        a fragment's first line) is unchanged.
        """
        helper = self._METHOD_HELPERS.get(method.upper())
        if helper is None:
            raise ValueError(
                f"{cell_id}: no Rails route helper for HTTP method {method!r} "
                f"-- known methods: {sorted(self._METHOD_HELPERS)}"
            )
        line = f"  {helper} '{url_path}', to: '{controller_name}#{action}' # cell: {cell_id}"
        if get_page is None:
            return line
        if helper == "get":
            raise ValueError(f"{cell_id}: a GET cell already serves GET {url_path!r}; it cannot have a get_page")
        if not _TO_RE.fullmatch(get_page):
            raise ValueError(f"{cell_id}: get_page {get_page!r} is not a 'controller#action' string")
        return f"  get '{url_path}', to: '{get_page}' # cell: {cell_id} (GET page)\n" + line

    def render_file(self, fragments: Mapping[str, str]) -> str:
        """Assemble the whole ``config/routes.rb`` from ``{cell_id:
        fragment}``, always sorting by ``cell_id`` at call time -- never
        trusting the mapping's own insertion order. Byte-identical for two
        calls with the same fragment set, regardless of collection order.

        Raises :class:`DuplicateRouteError` if two cells' fragments register
        the same URL -- Rails would silently dispatch only the first
        matching route, leaving the second cell unreachable, exactly the
        same defense-in-depth check the Laravel accumulator performs.
        """
        by_url: dict[str, list[str]] = {}
        for cell_id in sorted(fragments):
            match = _ROUTE_URL_RE.match(fragments[cell_id])
            if match:
                by_url.setdefault(match.group(1), []).append(cell_id)
        collisions = {url: ids for url, ids in by_url.items() if len(ids) > 1}
        if collisions:
            raise DuplicateRouteError(
                "config/routes.rb would register the same URL for more than one cell, so all "
                "but the first would be unreachable: "
                + "; ".join(f"{url!r} <- {', '.join(ids)}" for url, ids in sorted(collisions.items()))
            )
        sorted_lines = [fragments[cell_id] for cell_id in sorted(fragments)]
        body = "\n".join(sorted_lines)
        return _HEADER + (body + "\n" if body else "") + _FOOTER


def assemble_routes_file(fragments: Mapping[str, str]) -> EmittedFile:
    """Build the final, whole-manifest ``config/routes.rb``
    :class:`~fuzzlab.labgen.emitter.EmittedFile` from a cell-id-keyed
    fragment map -- a thin wrapper over :meth:`RouteAccumulator.render_file`,
    mirroring the Laravel accumulator's own convenience function."""
    accumulator = RouteAccumulator()
    content = accumulator.render_file(fragments)
    return EmittedFile(path="config/routes.rb", content=content.encode("utf-8"), role="route")


def served_routes(routes_rb: str) -> list[tuple[str, str, str]]:
    """Every ``(VERB, path, target)`` a rendered ``config/routes.rb`` registers
    -- the single source the live PA-0054 sweep enumerates (CC-LAB-0245),
    parsed from the exact file Rails loads, never from a crawl. Raises if a
    non-comment, non-structural line is not understood, so a new route form
    cannot silently fall out of the sweep."""
    routes: list[tuple[str, str, str]] = []
    for raw in routes_rb.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#") or stripped in ("end",) or stripped.startswith(
            "Rails.application.routes.draw"
        ):
            continue
        match = _SERVED_ROUTE_RE.match(raw)
        if match is None:
            raise ValueError(f"served_routes: unrecognized routes.rb line {raw!r}")
        verb, path, target, alt_path, alt_target = match.groups()
        if path is None:
            path, target = alt_path, alt_target
        if not path.startswith("/"):
            path = "/" + path
        routes.append((verb.upper(), path, target))
    return routes
