"""``php_current``: the first (reproduction) emitter (T-LAB0.4).

Implements :class:`fuzzlab.labgen.emitter.Emitter` for PHP by assembling
:mod:`fuzzlab.labgen.modules` fragments per cell, per ``CR-LAB-0001``
Addendum C's module-composition correction.

**Scope, stated plainly (per the T-LAB0.4 task brief):** this emitter does
**not** reproduce all ~30 of today's real ``puppy-fort-factory/`` pages --
that migration is separate, later, larger work (tracked in
``docs/LAB_PHASE_0_PLAN.md`` T-LAB0.7/Phase 3). It renders one illustrative
vulnerable/secure pair -- a raw string-concatenation numeric-literal SQL
lookup and its ``param_bind``-secured twin -- to prove the module-composition
model produces real, syntactically valid, byte-deterministic PHP end to end,
which is this task's actual exit criterion.
"""

from __future__ import annotations

from typing import Any

from fuzzlab.labgen.emitter import EmittedFile, EmittedFiles, Emitter
from fuzzlab.labgen.modules import COMPLEXITIES, SINKS, SOURCES, TRANSFORMS
from fuzzlab.labgen.schema import Cell, SinkContext

#: sink_context families this emitter knows how to render. Any other
#: (vuln_class, sink_context) pair is declared unsupported via `supports()`.
_SUPPORTED_VULN_CLASSES = {"sqli"}
_SUPPORTED_SINK_FAMILIES = {"sql_numeric_literal"}

#: The one illustrative lookup this Phase-0 emitter models: a single-row
#: fetch by an integer id column, mirroring the shape
#: `lab/manifests/example_phase0_scaffold.yaml`'s LABGEN-EX-0001/0002 cells
#: describe (product.php's `?id=`).
_TABLE = "products"
_COLUMN = "id"
_PARAM_NAME = "id"
_VAR_NAME = "id"


class PhpCurrentEmitter(Emitter):
    """Renders a :class:`Cell` to a single PHP page via module composition.

    ``render()`` never falls back to a default sink/transform silently: an
    op or sink_context this emitter has no module for raises, rather than
    guessing -- the same "fail loud on an authoring gap" discipline
    ``fuzzlab.labgen.verdict`` already uses for the safety matrix.
    """

    def supports(self, vuln_class: str, sink_context: SinkContext) -> bool:
        return vuln_class in _SUPPORTED_VULN_CLASSES and sink_context.family in _SUPPORTED_SINK_FAMILIES

    def render(self, cell: Cell) -> EmittedFiles:
        if not self.supports(cell.vuln_class, cell.sink_context):
            raise ValueError(
                f"{cell.cell_id}: unsupported for php_current "
                f"(class={cell.vuln_class!r}, sink_context.family={cell.sink_context.family!r}) "
                "-- callers must check supports() before calling render(), per T-LAB0.4's "
                "declare-unsupported-and-skip rule"
            )

        ctx: dict[str, Any] = {
            "var_name": _VAR_NAME,
            "param_name": _PARAM_NAME,
            "table": _TABLE,
            "column": _COLUMN,
            "handler_name": f"handle_{cell.cell_id.lower().replace('-', '_')}",
        }

        source_result = SOURCES["get_param"].render(ctx)
        ctx = source_result.context

        # An empty transform pipeline means "identity" (the raw value is
        # used as-is) -- every op in a non-empty pipeline runs in order,
        # each free to publish new context keys for the next module/the
        # sink (mirrors fuzzlab.labgen.verdict.verdict()'s own ordered walk
        # over pipeline.ops).
        applied_ops = list(cell.transform.ops) or ["identity"]
        transform_code_blocks: list[str] = []
        for op in applied_ops:
            if op not in TRANSFORMS:
                raise ValueError(
                    f"{cell.cell_id}: php_current has no transform module for op {op!r} "
                    f"-- known ops: {sorted(TRANSFORMS)}"
                )
            transform_result = TRANSFORMS[op].render(ctx)
            ctx = transform_result.context
            transform_code_blocks.append(transform_result.code)

        sink_result = SINKS["sql_numeric_lookup"].render(ctx)

        body = _indent_block(
            "\n".join((source_result.code, *transform_code_blocks, sink_result.code)),
            "    ",
        )
        complexity_result = COMPLEXITIES["single_statement"].render({**ctx, "body": body})

        composition = " -> ".join(("get_param", *applied_ops, "sql_numeric_lookup", "single_statement"))
        php_source = (
            "<?php\n"
            f"// Generated by fuzzlab.labgen.emitters.php_current for cell {cell.cell_id}\n"
            f"// Module composition: {composition}\n"
            "\n"
            f"{complexity_result.code}"
        )
        path = f"generated/{cell.cell_id.lower()}.php"
        return (EmittedFile(path=path, content=php_source.encode("utf-8"), role="page"),)


def _indent_block(text: str, prefix: str) -> str:
    """Indent every non-blank line of ``text`` by ``prefix``. Deterministic
    and dependency-free -- no reliance on a Jinja2 filter's own defaults."""
    lines = text.split("\n")
    return "\n".join((prefix + line) if line else line for line in lines)
